[tool.poetry]
name = "SPIMquant"
version = "0.1.0"
description = "Snakebids app for quantitative analysis of SPIM (lightsheet) brains"
readme = "README.md"
license = "MIT"
authors = [
    "Ali Khan <alik@robarts.ca>"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
snakemake = ">=8.0.0"
snakebids = ">=0.12.0"
pulp = "<2.8.0"
pandas = [
    { version = "<=2.0.3", python = "<3.9" },
    { version = ">=2.1.1", python = ">=3.12" },
]
numpy = "^1.26.4"
dask = "^2024.2.0"
zarr = "^2.17.0"
scipy = "^1.12.0"
jupyterlab = "^4.1.1"
matplotlib = "^3.8.3"
scikit-image = "^0.22.0"
scikit-learn = "^1.4.1.post1"
seaborn = "^0.13.2"
stardist = "^0.8.5"
dask-image = "^2023.8.1"
ome-zarr = "^0.8.3"
ome-zarr-neuro = {git = "https://github.com/khanlab/ome-zarr-neuro", develop = true}
pybids = {git = "https://github.com/bids-standard/pybids", rev = 'master' }
attrs = "22.2.0"
napari = "0.4.19"
napari-ome-zarr = "^0.5.2"
pyqt5 = "=5.15.10"   
pyqt5-qt5 = "=5.15.2"
cellpose = "^3.0.7"
sparse = "^0.15.1"
napari-nibabel = "^0.1.0"

[tool.poetry.scripts]
spimquant = "spimquant.run:main"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
